### ISSUE TITLE
Needs more hash

### ISSUE THREAD

**Issue by josephdburdick** [disintegrator/gulp-buster#1]
Hi @disintegrator, this plugin is exactly what I'm looking for and I have it running through, creating a dist folder and a minified CSS file per your instruction but it doesn't append any sort of hash to the end of the file references within the CSS.

A colleague of mine altered the index.js of your plugin to append a simple string to the end of the outputted CSS:

``` js
'use strict';

var path = require('path');
var url = require('url');

var _ = require('lodash');
var es = require('event-stream');
var rs = require('replacestream');

var defaults = {
  hashes: {},
  assetRoot: '',
  assetURL: '/',
  tokenRegExp: /ASSET{(.*?)}/g,
  hashLength: 8
};


var plugin = function(options) {
  var opts = _.extend({}, defaults, options);
  var replaceFunc = function(m, p1) {
    var p = path.join(opts.assetRoot, p1);
    var digest = (opts.hashes[p] || '45674');
    //var digest = (opts.hashes[p] || '');
    var u = url.parse(opts.assetURL);
    u.pathname += p1;
    if (digest) {
      u.query = _.extend({}, u.query, {v: digest.substr(0, opts.hashLength)});
    }
    return url.format(u);
  };
  return es.map(function(file, cb) {
    var out = file;
    if (file.isNull()) { return cb(null, out); }
    if (file.isBuffer()) {
      file.contents = new Buffer(String(file.contents)
          .replace(opts.tokenRegExp, replaceFunc));
    }
    else if (file.isStream()) {
      out = file.pipe(rs(opts.tokenRegExp, replaceFunc));
    }
    return cb(null, out);
  });
};

module.exports = plugin;
```

This plugin does alter the URL of each asset to be an absolute path. What gets us is that within your index.js there's no mention of any hash production. Should we add our own gulp hash plugin and append it instead of the numbers found within your replaceFunc function [ var digest = (opts.hashes[p] || '45674');]?

**Comment by disintegrator** [comment]
Hi @josephdburdick I think what you're missing is dropping in [gulp-hasher](https://github.com/disintegrator/gulp-hasher) plugin or similar? This plugin does not do any ahead-of-time hash calculation but relies on an external source that provide an assetReference-to-hash mapping.

Could you please follow the `NOTICE` comments below and let me know if I made sense? This example is taken from the README where I mention the requirement for `gulp-hasher` or similar. If it is still not clear, can you suggest some way I could clarify further? (Maybe I should add a full Gulpfile example?)

```
var hasher = require('gulp-hasher');   // <=== NOTICE 1: probably needed this?

gulp.task('images', function() {
  return gulp.src('assets/images/**/*')
    .pipe(imagemin({
      progressive: true,
      svgoPlugins: [{removeViewBox: false}],
      use: [pngquant()]
    }))
    .pipe(gulp.dest('dist/assets/images/'))
    .pipe(hasher());  // <=== NOTICE 2: calculates hash for each img file and caches it
});

gulp.task('styles', ['images'], function() {
  return gulp.src('assets/styles/themes/*/style.less')
    .pipe(autoprefixer())
    .pipe(buster({
      assetRoot: path.join(__dirname, 'dist'),
      hashes: hasher.hashes     //<=== NOTICE 3: gulp-hasher plugin exposes hashes map
    }))
    .pipe(gulp.dest('dist/assets/styles/'))
    .pipe(hasher())  <==== NOTICE 4: calculates hash for each css file if we need later
    .pipe(minifyCss())
    .pipe(rename({extname: '.min.css'}))
    .pipe(gulp.dest('dist/assets/styles/'))
    .pipe(hasher());
});
```

**Comment by josephdburdick** [comment]
Hi @disintegrator when I get to my desk tomorrow I will relay to you information regarding our use of gulp-hasher. I'm 90% sure we used it but perhaps we have the wrong configuration for it.

**Comment by disintegrator** [comment]
The stateful nature of gulp-hasher might be a source of confusion. Given my example above:
- Before `NOTICE 1`, `hasher.hashes` is empty
- Before `NOTICE 3`, `hasher.hashes` contains every image that was minified and it's md5 digest since styles depends on images
- After `NOTICE 4`, `hasher.hashes` ALSO contains the _unminified_ CSS file paths and their md5 digests under `'dist/assets/styles/'`
- By the end of the styles task, `hasher.hashes`ALSO contains the _minified_ CSS file paths and their md5 digests under `'dist/assets/styles/'`

It's probably worthwhile having something like this through stream to observe the hashes cache as your gulp tasks execute

```
var es = require('event-stream');
var hasher = require('gulp-hasher');
var gutil = require('gulp-util');

var printCache = function(tag) {
  return es.through(function(data) {
    gutil.log('hasher@' + tag)
    gutil.log(JSON.stringify(hasher.hashes, null, 2))
    this.emit('data', data);
  });
}

gulp.task('styles', ['images'], function() {
  return gulp.src('assets/styles/themes/*/style.less')
    .pipe(printCache('styles1'))
    .pipe(autoprefixer())
    .pipe(buster({
      assetRoot: path.join(__dirname, 'dist'),
      hashes: hasher.hashes
    }))
    .pipe(gulp.dest('dist/assets/styles/'))
    .pipe(hasher())
    .pipe(printCache('styles2'))
    .pipe(minifyCss())
    .pipe(rename({extname: '.min.css'}))
    .pipe(gulp.dest('dist/assets/styles/'))
    .pipe(hasher())
    .pipe(printCache('styles3'));
});
```

**Comment by josephdburdick** [comment]
Ok, well let's start from the beginning, I have an undefined error on the `paths` object. This was the first workaround I tried to make.

``` js
.pipe($.buster({
      assetRoot: path.join(__dirname, 'app/styles'),
      hashes: hasher.hashes     // since images task has run we can pass in the hashes object
    }))
```

The error output:

``` js
[01:09:00] ReferenceError: path is not defined
    at Gulp.gulp.task.gulp.src.pipe.reload.stream (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/gulpfile.js:23:18)
    at module.exports (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/gulpfile.js:130:8)
    at module.exports (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Applications/MAMP/htdocs/Code/Github/josephdburdick/node/gulp-cachebuster/node_modules/gulp/node_modules/orchestrator/index.js:279:18
```

**Comment by disintegrator** [comment]
Couple of points @josephdburdick 
- I'm not sure where the `$` in `$.buster` comes from
- I'm guessing you're missing a `var path = require('path')`

Maybe start by getting a gulp workflow working without buster and hasher then plug them in where needed?

If you can put your gulpfile up in a gist I can probably help pinpoint your problem. How's that sound?

**Comment by josephdburdick** [comment]
@disintegrator I'm going to try again in a repo now that already has a working gulp workflow and report back. Thank you for the offer of looking at this in detail.

Btw, $.buster is a reference to your plugin from the plugin gulp-load-plugins that allows for less var declarations at the top of the gulpfile by reading through the package.json and reading off what's a gulp plugin and what's not.

**Comment by josephdburdick** [comment]
@disintegrator Here's my latest attempt: https://gist.github.com/josephdburdick/4d31211ffb68e8066b01

**Comment by disintegrator** [comment]
@josephdburdick I've left a few comments on your gist - I hope it helps. I'm not sure I can offer anymore insight without replicating your environment (I wish I had the time). Since you now have hasher and buster in your tasks, it's probably a matter of tinkering with their placement to get the desired effect. I know that's not great advice and I'm still wondering if there is a better way to express this in the README. I might just provide my gulpfile as an example and ping you back.

**Comment by josephdburdick** [comment]
Thank you for your guidance. I'm closing this issue.
